# Generated by Django 4.2.4 on 2023-08-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
